version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mon_projet_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: ./backend  # Chemin vers le dossier backend
      dockerfile: Dockerfile # Le nom du Dockerfile dans le dossier backend
    container_name: backend-container
    volumes:
      - ./backend/src:/var/www/html  # Lier le code source du backend dans le container
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge